### ISSUE TITLE
HW10 Ready for grading

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw-Hall-Shirlett#10]
See ![HW10](https://github.com/Shirlett/STAT545-hw-Hall-Shirlett/tree/master/HW10)

**Comment by abishekarun** [comment]
Hi @shirlett,

Really nice work scraping data from besplaces.net and working on bird species task for your homework 10! I just have a few comments for you:

**Scraping the web**
- It was nice to see you obtain the data in a table and your data cleaning was neat and understandable. 
- It was great to see how you related the fear of eating out with population from your plot. 
  + I felt that more places could have been plotted in the graph as 10 out of 50 is less to arrive at a relationship.
  + I also felt that some of the places this interpretation was not strictly followed. Some anomalies I observed were Niagara falls and Salt lake city. I felt that these places could have been explored and other parameter affecting the rank could have been obtained.

**Articles Published on Bird Species**
- It was great to see you obtain the bird species and the number of articles published for each of them. 
- It was also nice to see you mention the popular and least popular bird species from your data.
- You have used **plosword()**. I didn't know about this function. If it was a custom function that you had developed, it would have been nice to see the code for that. If it was inbuilt function, thank you  for showing how to use it.

It was great to see you mention the difficulties that you had faced and also provide the solutions that you found. Also it was nice to see you mention the resources that helped you find these solutions as well. I would suggest you to provide the link to the markdown file in the issue as it will help instructors in finding the file.

Overall you did a great job on your final homework, and I hope you enjoy your winter break!

Cheers
abishekarun
