### ISSUE TITLE
Please add me as a colloborator

### ISSUE THREAD

**Issue by Shirlett** [Shirlett/STAT545-hw-Hall-Shirlett#5]
@farihakhan  
@margotgunning

**Comment by margotgunning** [comment]
Hi @Shirlett,

I added you as a collaborator to my HW repo for STAT545; it says in my settings that you have accepted the invitation to be a collaborator.  Do you need me to resend it?

M

**Comment by Shirlett** [comment]
It's ok @margotgunning .
The invite was buried under some junk mail.
I just saw it a few minutes ago after I sent you the message through Github.
Thanks!

**Comment by farihakhan** [comment]
@margotgunning Hey can  you add me to your collaborators too?

**Comment by margotgunning** [comment]
Hey @farihakhan I just resent your invite.  I think some people have been getting their invites lost in their junk mail, so maybe check that out if you can't find it.

M
